name: lilac_dart
description: RTS micro-management puzzles written in Dart.
# version: 0.1.0
# homepage: https://imperialoctopus.com/
# author: Zoey Child <imperialoctopus@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  vector_math: any
  pedantic: ^1.4.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
